services:
  tidyquest:
    build: .
    container_name: tidyquest
    ports:
      - "3020:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Gdo4vlhhZNOz6RIfZnvZVSluTQgQokPDF50UmJy7xww=
      - TZ=Europe/Sofia
    volumes:
      - /TidyQuest/data:/app/data
    restart: unless-stopped